name: sharexev2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  onboarding: ^4.0.2
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  equatable: ^2.0.7
  web_socket_channel: ^2.4.0
  cloud_firestore: ^6.0.0
  intl: ^0.19.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  easy_helpers: ^0.0.14
  dio: ^5.9.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Đảm bảo file icon.png tồn tại
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff" # Màu nền, thay bằng mã hex bạn muốn
    theme_color: "#000000" # Màu chủ đạo, thay bằng mã hex bạn muốn
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 50
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/commons/
    - assets/images/logos/
    - assets/images/widgets/
    - assets/icon/ # Thêm thư mục icon để Flutter nhận diện