// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAyh6z1-YgBycnKimDztKCCmcVxpGknk',
    appId: '1:956934486223:web:f944ffdaf6faef6c521fba',
    messagingSenderId: '956934486223',
    projectId: 'sharexev2',
    authDomain: 'sharexev2.firebaseapp.com',
    storageBucket: 'sharexev2.firebasestorage.app',
    measurementId: 'G-RBYNT6BNQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihuq5_wJBH4HoTV3h0y_ejKzzqhUhrS4',
    appId: '1:956934486223:android:e7370301cf81e60e521fba',
    messagingSenderId: '956934486223',
    projectId: 'sharexev2',
    storageBucket: 'sharexev2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6jSrltN7UyoNUYB2oWo1-PdyFo8AlrM',
    appId: '1:956934486223:ios:49ec9ce820a830b4521fba',
    messagingSenderId: '956934486223',
    projectId: 'sharexev2',
    storageBucket: 'sharexev2.firebasestorage.app',
    iosBundleId: 'com.example.sharexev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy6jSrltN7UyoNUYB2oWo1-PdyFo8AlrM',
    appId: '1:956934486223:ios:49ec9ce820a830b4521fba',
    messagingSenderId: '956934486223',
    projectId: 'sharexev2',
    storageBucket: 'sharexev2.firebasestorage.app',
    iosBundleId: 'com.example.sharexev2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPAyh6z1-YgBycnKimDztKCCmcVxpGknk',
    appId: '1:956934486223:web:d5c208150fa7b4de521fba',
    messagingSenderId: '956934486223',
    projectId: 'sharexev2',
    authDomain: 'sharexev2.firebaseapp.com',
    storageBucket: 'sharexev2.firebasestorage.app',
    measurementId: 'G-CVZF10DTHL',
  );
}
